### PR TITLE
Add testnet toggle to extension

### PR DESCRIPTION
**Pull request by tvorogme**
ezgif-2-d17e87ee6a

As dApp developer I need to test my web application with testnet on extension wallet. 
This feature has metamask / bsc wallet, so TON also needed it :)

### CODE REVIEW

**Comment by tvorogme** [comment]
@tolya-yanot please review / comment. 

Maybe toggle button need renaming or changing font-size.

**Comment by designervoid** [comment]
полезная кнопка)

**Comment by futpib** [comment]
Ura suka davai davai blyat

**Comment by tolya-yanot** [comment]
Thanks for the PR, this code was not merged into the master, but the functionality of switching between testnet and mainnet in the extension was implemented in the master

https://github.com/toncenter/ton-wallet#switch-between-mainnettestnet-in-extension

**Pull request closed without merging**
